<?php

function get_install_input($varname, $key, $data) {
	$value = __($_POST['config'][$varname][$key]);
	return _get_input($value, $varname, $key, $data, true);
}

function get_update_input($varname, $key, $data) {
	$value = __($data['direct']) ? $GLOBALS[$key] : $GLOBALS[$varname][$key];
	return _get_input($value, $varname, $key, $data);
}

function ext_get_update_input($varname, $key, $data) {
	$value = $GLOBALS['xconf'][$key];
	return _get_input($value, $varname, $key, $data);
}

function setup_input($varname, $key, $data) {
	$input = $attrib = "";
	
	//--
	// Default field
	$direct = __($data['direct']);
	if (isset($_POST['config'][$varname][$key])) {
		// POST value 
		$default = $_POST['config'][$varname][$key];
	} else if ($direct && isset($GLOBALS[$key])) { 
		// board installed and the variable specified is directly accessible ($sqluser, $sqlpass,...)
		$default = $GLOBALS[$key];
	} else if (!$direct && isset($GLOBALS[$varname][$key])) { 
		// board installed and the $config / $hacks ... field is accessible
		$default = $GLOBALS[$varname][$key];
	} else {
		$default = null;
	}
	
	return input($varname, $key, $data, $default);
}

function setup_input_section($var_name, $section) {
	return input_section($var_name, $section, 'setup_input');
}

function get_schema() { return json_decode(file_get_contents("install/schema.json"), true); }

function get_config_sql_layout() {
	$schema = get_schema();
	$x = ['__sql' => $schema['__sql']];
	return get_config_layout($x, 'setup_input');
}

function get_config_main_layout() {
	$schema = get_schema();
	// We don't need the SQL connection options here
	unset($schema['__sql']);
	
	return get_config_layout($schema, 'setup_input');
}

function ext_update_config($extName) {
	$opts = ext_read_settingspage($extName);
	$output = "<?php # Autogenerated config file \r\n".generate_config($opts, 'ext_get_update_input');
	file_put_contents("extensions/{$extName}.abx/config.php", $output);
}

function setup_generate_config($mode = false) {
	$schema    = get_schema();
	$inputfunc = $mode ? 'get_update_input' : 'get_install_input';
	
	return 
"<?php
# this file is auto-generated by the installer and by the upgrade script
# if you add any custom code here (which actually happens in some acmlmboards, believe it or not) it will be lost!
# note that with the upgrade process custom \$config, \$hacks and \$x_hacks keys will be preserved

".generate_config($schema, $inputfunc)."

	// Are we using SSL?
	if (isset(\$_SERVER['HTTPS']) && \$_SERVER['HTTPS'] != 'off')
		\$config['board-url'] = str_replace(\"http://\", \"https://\", \$config['board-url']);
";
}