<?php

const GCL_SQL    = 1;
const GCL_CONFIG = 2;
function setup_get_config_layout($mode = 0) {
	$schema = new schema("config", "install/schema.json");
	// Special case for the separate SQL credentials screen
	if ($mode == GCL_SQL)
		$schema->include_var("sqlconfig");
	else if ($mode == GCL_CONFIG)
		$schema->exclude_var("sqlconfig");
	
	$schema->vars = __($_POST['config']);
	$schema->vars_fallback = $GLOBALS;
	return $schema->make_config_html();
}

function setup_generate_ext_config($extName) {
	// This goes off $xconf being defined as a global variable.
	$schema = ext_read_schema("xconf", $extName);
	$schema->vars = $GLOBALS; // $xconf is a global variable
	$output = "<?php # Autogenerated config file \r\n".$schema->make_php();
	file_put_contents("extensions/{$extName}.abx/config.php", $output);
}

function setup_generate_config() {
	$schema = new schema("config", "install/schema.json");
	$schema->vars = __($_POST['config']);
	$schema->vars_fallback = $GLOBALS;
	
	return 
"<?php
# this file is auto-generated by the installer and by the upgrade script
# if you add any custom code here (which actually happens in some acmlmboards, believe it or not) it will be lost!
# note that with the upgrade process custom \$sqlconfig, \$config, \$hacks and \$x_hacks keys will be preserved

".$schema->make_php()."

	// Compatibility aliasing
	extract(\$sqlconfig); // (\$sqlhost, \$sqluser, \$sqlpass, \$dbname)
	\$sqldebuggers = \$config['sqldebuggers'];
	
	// Are we using SSL?
	if (isset(\$_SERVER['HTTPS']) && \$_SERVER['HTTPS'] != 'off')
		\$config['board-url'] = str_replace(\"http://\", \"https://\", \$config['board-url']);
";
}